import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body>
        <header>
          {/* 페이지 이동 */}
          <Link href={"/"}>index</Link>&nbsp;
          <Link href={"/search"}>search</Link>&nbsp;
          <Link href={"/book/1"}>book/1</Link>
        </header>
        {/* 중괄호 children이라고 해서 이런 레이아웃 안쪽으로 페이지 컴포넌트들을 렌더링 함. */}
        {/* 레이아웃 안에 페이지가 어디에 위치할 건지를 설정 */}
        {children}
      </body>
    </html>
  );
}
