import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 중괄호 children이라고 해서 이런 레이아웃 안쪽으로 페이지 컴포넌트들을 렌더링 함. */}
      {/* 레이아웃 안에 페이지가 어디에 위치할 건지를 설정 */}
      <body>{children}</body>
    </html>
  );
}
